web:
  image: nginx
  volumes:
   - ./templates:/etc/nginx/templates
   - ./_site:/usr/share/nginx/html
  ports:
   - "80:80"
  environment:
   - NGINX_HOST=foobar.com
   - NGINX_PORT=80
  restart: always
