web:
  image: nginx
  volumes:
   - ./templates:/etc/nginx/templates  # NOTE: idk what this is for
   - ./_site:/etc/nginx/html/
   - /root/certs_imars_usf_edu:/etc/nginx/certs
   - ./nginx_conf:/etc/nginx/conf.d
  ports:
   - "80:80"
   - "443:443"
  environment:
   - NGINX_HOST=imars.usf.edu
   - NGINX_PORT=80
  restart: always

