version: "3.3"
services:
  web:
    image: nginx
    volumes:
      - type: bind
        source: ./templates
        target: /etc/nginx/templates  # NOTE: idk what this is for
      - type: bind
        source: ./_site
        target: /etc/nginx/html/  # main jekyll website
      - type: bind
        source: /root/certs_imars_usf_edu
        target: /etc/nginx/certs  # ssl certs
      - type: bind
        source: ./nginx_conf
        target: /etc/nginx/conf.d  # nginx server config
      - type: volume
        source: user_homes # ./_public_html
        target: /user_sites  # user sites
      - type: volume
        source: fk
        target: /srv/imars-objets/fk
      - type: volume
        source: fgb
        target: /srv/imars-objects/fgb

    ports:
     - "80:80"
     - "443:443"
    environment:
     - NGINX_HOST=imars.usf.edu
     - NGINX_PORT=80
    restart: always
volumes:
  user_homes:
    driver_opts:
      type: "nfs"
      o: "addr=yinmaster,ro,soft,intr,tcp,nfsvers=4,noacl"
      device: ":/yin/homes"
  fgb:
    driver_opts:
      type: "nfs"
      o: "addr=thing1master,ro,intr,tcp,nfsvers=4,noacl"
      device: ":/fgb"
  fk:
    driver_opts:
      type: "nfs"
      o: "addr=thing1master,ro,intr,tcp,nfsvers=4,noacl"
      device: ":/fk"
